### ISSUE TITLE
Returning a whole lot of empty

### ISSUE THREAD

**Issue by jelmerkk** [rjblake/tado#1]
Hi, thanks for building the new script! I'm trying to get it to work on my RPi, and I'm encountering these errors. It may be that Tado changed again, *or I'm just not implementing it right...*

Token Age: 21 | Used cached token | PHP Notice:  Undefined index: homes in /home/pi/domoticz/scripts/tado.php on line 129
PHP Notice:  Undefined index: type in /home/pi/domoticz/scripts/tado.php on line 455
PHP Notice:  Undefined offset: 0 in /home/pi/domoticz/scripts/tado.php on line 297
PHP Notice:  Undefined index: setting in /home/pi/domoticz/scripts/tado.php on line 317
PHP Notice:  Undefined index: sensorDataPoints in /home/pi/domoticz/scripts/tado.php on line 318
PHP Notice:  Undefined index: sensorDataPoints in /home/pi/domoticz/scripts/tado.php on line 319
PHP Notice:  Undefined index: sensorDataPoints in /home/pi/domoticz/scripts/tado.php on line 320
HomeID:  - ZoneID:  - Temp&Humidity: ;;2 - Setpoint:

**Comment by rjblake** [comment]
I think they did something again. I have just taken a look at my install and this stopped working around 09:30 CEST. Will do some checking tonight to see if I can work out what they did to break it

**Comment by rjblake** [comment]
I have updated the code and is working on my setup. Tado changed the 'secret'  again and the client_id. From the looks of things, this is for a preview of the API so I expect it will break again when officially released, but at least should be documented properly
