### ISSUE TITLE
switch to new tado authentication server

### ISSUE THREAD

**Issue by elmi82** [rjblake/tado#2]
tado is discontinuing the old OAuth2 endpoints at `my.tado.com`. Starting March 2019, authentication will require retrieving access and refresh tokens from `auth.tado.com`. The client `public-api-preview` can be used as is (with the same client secret) on the new endpoint.

The new authentication will also be a standard OAuth2 system, but will use JWT as a format for refresh tokens. So be aware that this will increase the size of the refresh tokens.

Additionally, the new endpoints implement [refresh token rotation](https://tools.ietf.org/html/rfc6749#section-10.4). A new refresh token is issued with every access token refresh response. The previous refresh token is invalidated.

**Comment by rjblake** [comment]
@elmi82 - many thanks for this heads up on the coming changes. Guess I'll need to review my code and amend accordingly (if I can find time). Do you know if this is already active/available to use and test?

**Comment by elmi82** [comment]
@rjblake - yes, it's already available.

**Comment by rjblake** [comment]
This has been incorporated in the code - I'm a bit late in closing this :(
